import 'dart:io';

class CliInstallResult {
  final bool ok;
  final String message;
  final String? path;
  const CliInstallResult({
    required this.ok,
    required this.message,
    this.path,
  });
}

/// Installs and removes a `/usr/local/bin/sweep` (or
/// `$HOMEBREW_PREFIX/bin/sweep`) wrapper that forwards every arg to
/// the GUI .app's binary in `--headless` mode.
///
/// macOS won't let us write to `/usr/bin` (SIP-protected). The standard
/// safe targets are:
///
///   • `/opt/homebrew/bin` — Apple Silicon Homebrew prefix, owned by
///     the user; **no admin needed**.
///   • `/usr/local/bin` — Intel Homebrew prefix and the historical
///     "third-party CLI tool" location. Needs admin to write unless the
///     user has chowned it.
///
/// We probe `/opt/homebrew/bin` first and use it when writable;
/// otherwise we fall back to `/usr/local/bin` and run the move via
/// `osascript with administrator privileges`.
class CliInstallerService {
  static const _toolName = 'sweep';

  /// The wrapper script body. Walks common .app install locations so
  /// the same wrapper survives if the user moves Sweep.app between
  /// `/Applications` and `~/Applications`. `exec` so signals + exit
  /// codes pass through.
  static const _wrapperContent = '''#!/bin/sh
# Sweep command-line wrapper. Forwards every argument to the .app
# binary in --headless mode. Generated by CliInstallerService.
for candidate in \\
  "/Applications/Sweep.app" \\
  "\$HOME/Applications/Sweep.app"; do
  if [ -x "\$candidate/Contents/MacOS/Sweep" ]; then
    exec "\$candidate/Contents/MacOS/Sweep" --headless "\$@"
  fi
done
echo "Sweep.app not found in /Applications or ~/Applications" >&2
exit 127
''';

  /// Write the wrapper to whichever bin dir is most natural. Returns
  /// where the wrapper landed, or a failure with a message suitable
  /// for a SnackBar.
  Future<CliInstallResult> install() async {
    final target = await _resolveTarget();
    if (target == null) {
      return const CliInstallResult(
        ok: false,
        message: 'No suitable bin directory found. '
            'Expected /opt/homebrew/bin or /usr/local/bin.',
      );
    }
    final tmp = '${Directory.systemTemp.path}/sweep-cli-'
        '${DateTime.now().millisecondsSinceEpoch}';
    try {
      await File(tmp).writeAsString(_wrapperContent, flush: true);
    } catch (e) {
      return CliInstallResult(
        ok: false,
        message: 'Could not stage wrapper to $tmp: $e',
      );
    }

    if (target.needsAdmin) {
      // mv + chmod inside one osascript call so we get a single auth prompt.
      final escapedTmp = _escapeForApplescript(tmp);
      final escapedTarget = _escapeForApplescript(target.path);
      final cmd =
          '/bin/mv \\"$escapedTmp\\" \\"$escapedTarget\\" && '
          '/bin/chmod +x \\"$escapedTarget\\"';
      final r = await Process.run('osascript', [
        '-e',
        'do shell script "$cmd" with administrator privileges',
      ]);
      if (r.exitCode != 0) {
        try {
          await File(tmp).delete();
        } catch (_) {/* non-fatal */}
        return CliInstallResult(
          ok: false,
          message: 'Admin install failed: '
              '${r.stderr.toString().trim().isEmpty ? "user cancelled" : r.stderr.toString().trim()}',
        );
      }
    } else {
      try {
        await File(tmp).rename(target.path);
        await Process.run('chmod', ['+x', target.path]);
      } catch (e) {
        return CliInstallResult(
          ok: false,
          message: 'Install to ${target.path} failed: $e',
        );
      }
    }

    return CliInstallResult(
      ok: true,
      message: 'Installed `sweep` at ${target.path}.',
      path: target.path,
    );
  }

  Future<CliInstallResult> uninstall() async {
    // Try every candidate target rather than re-resolving — the user
    // may have installed under a different prefix at a different time.
    final candidates = [
      '/opt/homebrew/bin/$_toolName',
      '/usr/local/bin/$_toolName',
    ];
    String? removed;
    String? failure;
    for (final p in candidates) {
      final f = File(p);
      if (!await f.exists()) continue;
      try {
        await f.delete();
        removed = p;
      } catch (_) {
        // Likely owned by root; try osascript.
        final r = await Process.run('osascript', [
          '-e',
          'do shell script "/bin/rm -f \\"${_escapeForApplescript(p)}\\"" with administrator privileges',
        ]);
        if (r.exitCode == 0) {
          removed = p;
        } else {
          failure = r.stderr.toString().trim();
        }
      }
    }
    if (removed != null) {
      return CliInstallResult(
        ok: true,
        message: 'Removed wrapper from $removed.',
        path: removed,
      );
    }
    if (failure != null) {
      return CliInstallResult(
        ok: false,
        message: 'Could not remove wrapper: $failure',
      );
    }
    return const CliInstallResult(
      ok: true,
      message: 'No wrapper installed — nothing to remove.',
    );
  }

  /// True when one of the candidate wrapper paths already exists. The
  /// menu bar uses this to swap "Install" ↔ "Uninstall".
  Future<bool> isInstalled() async {
    for (final p in const [
      '/opt/homebrew/bin/$_toolName',
      '/usr/local/bin/$_toolName',
    ]) {
      if (await File(p).exists()) return true;
    }
    return false;
  }

  Future<_Target?> _resolveTarget() async {
    // Apple Silicon users with Homebrew → /opt/homebrew/bin (no admin).
    if (await Directory('/opt/homebrew/bin').exists() &&
        await _isWritable('/opt/homebrew/bin')) {
      return const _Target('/opt/homebrew/bin/$_toolName', needsAdmin: false);
    }
    // Intel users + everyone else → /usr/local/bin (admin).
    if (await Directory('/usr/local/bin').exists()) {
      return _Target(
        '/usr/local/bin/$_toolName',
        needsAdmin: !await _isWritable('/usr/local/bin'),
      );
    }
    return null;
  }

  Future<bool> _isWritable(String dir) async {
    final probe = File('$dir/.sweep-probe-'
        '${DateTime.now().microsecondsSinceEpoch}');
    try {
      await probe.writeAsString('');
      await probe.delete();
      return true;
    } catch (_) {
      return false;
    }
  }

  String _escapeForApplescript(String s) =>
      s.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
}

class _Target {
  final String path;
  final bool needsAdmin;
  const _Target(this.path, {required this.needsAdmin});
}
